# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BandPass.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_BandPass(object):
    def setupUi(self, MainWindow_BandPass):
        MainWindow_BandPass.setObjectName("MainWindow_BandPass")
        MainWindow_BandPass.resize(800, 600)
        self.centralwidget_BandPass = QtWidgets.QWidget(MainWindow_BandPass)
        self.centralwidget_BandPass.setObjectName("centralwidget_BandPass")
        self.frame_BandPass = QtWidgets.QFrame(self.centralwidget_BandPass)
        self.frame_BandPass.setGeometry(QtCore.QRect(0, 0, 791, 471))
        self.frame_BandPass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_BandPass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_BandPass.setObjectName("frame_BandPass")
        self.frame_2_BandPass = QtWidgets.QFrame(self.frame_BandPass)
        self.frame_2_BandPass.setGeometry(QtCore.QRect(240, 20, 301, 41))
        self.frame_2_BandPass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_BandPass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_BandPass.setObjectName("frame_2_BandPass")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2_BandPass)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 301, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.frame_3_BandPass = QtWidgets.QFrame(self.frame_BandPass)
        self.frame_3_BandPass.setGeometry(QtCore.QRect(10, 90, 761, 381))
        self.frame_3_BandPass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_BandPass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_BandPass.setObjectName("frame_3_BandPass")
        self.frame_4_BandPass = QtWidgets.QFrame(self.frame_3_BandPass)
        self.frame_4_BandPass.setGeometry(QtCore.QRect(10, 10, 221, 361))
        self.frame_4_BandPass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4_BandPass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4_BandPass.setObjectName("frame_4_BandPass")
        self.label_3_BandPass = QtWidgets.QLabel(self.frame_4_BandPass)
        self.label_3_BandPass.setGeometry(QtCore.QRect(20, 160, 59, 16))
        self.label_3_BandPass.setObjectName("label_3_BandPass")
        self.label_BandPass = QtWidgets.QLabel(self.frame_4_BandPass)
        self.label_BandPass.setGeometry(QtCore.QRect(10, 40, 59, 16))
        self.label_BandPass.setObjectName("label_BandPass")
        self.lineEdit_freq2_BandPass = QtWidgets.QLineEdit(self.frame_4_BandPass)
        self.lineEdit_freq2_BandPass.setGeometry(QtCore.QRect(150, 160, 51, 21))
        self.lineEdit_freq2_BandPass.setObjectName("lineEdit_freq2_BandPass")
        self.pushButton_test_BandPass = QtWidgets.QPushButton(self.frame_4_BandPass)
        self.pushButton_test_BandPass.setGeometry(QtCore.QRect(80, 220, 113, 32))
        self.pushButton_test_BandPass.setObjectName("pushButton_test_BandPass")
        self.label_4_BandPass = QtWidgets.QLabel(self.frame_4_BandPass)
        self.label_4_BandPass.setGeometry(QtCore.QRect(20, 10, 59, 16))
        self.label_4_BandPass.setObjectName("label_4_BandPass")
        self.lineEdit_ch_BandPass = QtWidgets.QLineEdit(self.frame_4_BandPass)
        self.lineEdit_ch_BandPass.setGeometry(QtCore.QRect(80, 70, 111, 21))
        self.lineEdit_ch_BandPass.setObjectName("lineEdit_ch_BandPass")
        self.lineEdit_time_BandPass = QtWidgets.QLineEdit(self.frame_4_BandPass)
        self.lineEdit_time_BandPass.setGeometry(QtCore.QRect(80, 40, 111, 21))
        self.lineEdit_time_BandPass.setTabletTracking(False)
        self.lineEdit_time_BandPass.setObjectName("lineEdit_time_BandPass")
        self.pushButton_setup_parameters_BandPass = QtWidgets.QPushButton(self.frame_4_BandPass)
        self.pushButton_setup_parameters_BandPass.setGeometry(QtCore.QRect(80, 110, 113, 32))
        self.pushButton_setup_parameters_BandPass.setObjectName("pushButton_setup_parameters_BandPass")
        self.checkBox_normalize_BandPass = QtWidgets.QCheckBox(self.frame_4_BandPass)
        self.checkBox_normalize_BandPass.setGeometry(QtCore.QRect(80, 90, 111, 20))
        self.checkBox_normalize_BandPass.setObjectName("checkBox_normalize_BandPass")
        self.pushButton_export_BandPass = QtWidgets.QPushButton(self.frame_4_BandPass)
        self.pushButton_export_BandPass.setGeometry(QtCore.QRect(40, 320, 121, 31))
        self.pushButton_export_BandPass.setObjectName("pushButton_export_BandPass")
        self.pushButton_Bandpass_BandPass = QtWidgets.QPushButton(self.frame_4_BandPass)
        self.pushButton_Bandpass_BandPass.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.pushButton_Bandpass_BandPass.setObjectName("pushButton_Bandpass_BandPass")
        self.lineEdit_freq1_BandPass = QtWidgets.QLineEdit(self.frame_4_BandPass)
        self.lineEdit_freq1_BandPass.setGeometry(QtCore.QRect(80, 160, 51, 21))
        self.lineEdit_freq1_BandPass.setObjectName("lineEdit_freq1_BandPass")
        self.label_2_BandPass = QtWidgets.QLabel(self.frame_4_BandPass)
        self.label_2_BandPass.setGeometry(QtCore.QRect(10, 70, 59, 16))
        self.label_2_BandPass.setObjectName("label_2_BandPass")
        self.lineEdit_fs_BandPass = QtWidgets.QLineEdit(self.frame_4_BandPass)
        self.lineEdit_fs_BandPass.setGeometry(QtCore.QRect(80, 10, 51, 21))
        self.lineEdit_fs_BandPass.setObjectName("lineEdit_fs_BandPass")
        self.frame_5_BandPass = QtWidgets.QFrame(self.frame_3_BandPass)
        self.frame_5_BandPass.setGeometry(QtCore.QRect(240, 10, 511, 361))
        self.frame_5_BandPass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5_BandPass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5_BandPass.setObjectName("frame_5_BandPass")
        self.widget = PlotWidget(self.frame_5_BandPass)
        self.widget.setGeometry(QtCore.QRect(0, 0, 501, 351))
        self.widget.setObjectName("widget")
        MainWindow_BandPass.setCentralWidget(self.centralwidget_BandPass)
        self.statusbar_BandPass = QtWidgets.QStatusBar(MainWindow_BandPass)
        self.statusbar_BandPass.setObjectName("statusbar_BandPass")
        MainWindow_BandPass.setStatusBar(self.statusbar_BandPass)

        self.retranslateUi(MainWindow_BandPass)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_BandPass)

    def retranslateUi(self, MainWindow_BandPass):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_BandPass.setWindowTitle(_translate("MainWindow_BandPass", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow_BandPass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Band Pass Filter </span></p></body></html>"))
        self.label_3_BandPass.setText(_translate("MainWindow_BandPass", "Freq"))
        self.label_BandPass.setText(_translate("MainWindow_BandPass", "Minute"))
        self.lineEdit_freq2_BandPass.setText(_translate("MainWindow_BandPass", "24"))
        self.pushButton_test_BandPass.setText(_translate("MainWindow_BandPass", "test"))
        self.label_4_BandPass.setText(_translate("MainWindow_BandPass", "Fs"))
        self.lineEdit_ch_BandPass.setText(_translate("MainWindow_BandPass", "0-2120"))
        self.lineEdit_time_BandPass.setText(_translate("MainWindow_BandPass", "0"))
        self.pushButton_setup_parameters_BandPass.setText(_translate("MainWindow_BandPass", "Confirm"))
        self.checkBox_normalize_BandPass.setText(_translate("MainWindow_BandPass", "Normalization"))
        self.pushButton_export_BandPass.setText(_translate("MainWindow_BandPass", "Export"))
        self.pushButton_Bandpass_BandPass.setText(_translate("MainWindow_BandPass", "BandPass"))
        self.lineEdit_freq1_BandPass.setText(_translate("MainWindow_BandPass", "0.5"))
        self.label_2_BandPass.setText(_translate("MainWindow_BandPass", "Channel"))
        self.lineEdit_fs_BandPass.setText(_translate("MainWindow_BandPass", "500"))
from mplwidget import MplWidget
from pyqtgraph import PlotWidget
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_BandPass = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_BandPass()
    ui.setupUi(MainWindow_BandPass)
    MainWindow_BandPass.show()
    sys.exit(app.exec_())