# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'envelope.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_envelope(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget_envelope = QtWidgets.QWidget(MainWindow)
        self.centralwidget_envelope.setObjectName("centralwidget_envelope")
        self.frame_envelope = QtWidgets.QFrame(self.centralwidget_envelope)
        self.frame_envelope.setGeometry(QtCore.QRect(0, 10, 791, 471))
        self.frame_envelope.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_envelope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_envelope.setObjectName("frame_envelope")
        self.frame_2_envelope = QtWidgets.QFrame(self.frame_envelope)
        self.frame_2_envelope.setGeometry(QtCore.QRect(240, 20, 301, 41))
        self.frame_2_envelope.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_envelope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_envelope.setObjectName("frame_2_envelope")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2_envelope)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 301, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.frame_3_envelope = QtWidgets.QFrame(self.frame_envelope)
        self.frame_3_envelope.setGeometry(QtCore.QRect(10, 90, 761, 381))
        self.frame_3_envelope.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_envelope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_envelope.setObjectName("frame_3_envelope")
        self.frame_4_envelope = QtWidgets.QFrame(self.frame_3_envelope)
        self.frame_4_envelope.setGeometry(QtCore.QRect(10, 10, 221, 361))
        self.frame_4_envelope.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4_envelope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4_envelope.setObjectName("frame_4_envelope")
        self.label_3_envelope = QtWidgets.QLabel(self.frame_4_envelope)
        self.label_3_envelope.setGeometry(QtCore.QRect(10, 130, 59, 16))
        self.label_3_envelope.setObjectName("label_3_envelope")
        self.label_envelope = QtWidgets.QLabel(self.frame_4_envelope)
        self.label_envelope.setGeometry(QtCore.QRect(10, 40, 59, 16))
        self.label_envelope.setObjectName("label_envelope")
        self.lineEdit_freq2_envelope = QtWidgets.QLineEdit(self.frame_4_envelope)
        self.lineEdit_freq2_envelope.setGeometry(QtCore.QRect(140, 130, 51, 21))
        self.lineEdit_freq2_envelope.setObjectName("lineEdit_freq2_envelope")
        self.pushButton_test_envelope = QtWidgets.QPushButton(self.frame_4_envelope)
        self.pushButton_test_envelope.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.pushButton_test_envelope.setObjectName("pushButton_test_envelope")
        self.label_4_envelope = QtWidgets.QLabel(self.frame_4_envelope)
        self.label_4_envelope.setGeometry(QtCore.QRect(20, 10, 59, 16))
        self.label_4_envelope.setObjectName("label_4_envelope")
        self.lineEdit_ch_envelope = QtWidgets.QLineEdit(self.frame_4_envelope)
        self.lineEdit_ch_envelope.setGeometry(QtCore.QRect(80, 70, 111, 21))
        self.lineEdit_ch_envelope.setObjectName("lineEdit_ch_envelope")
        self.lineEdit_time_envelope = QtWidgets.QLineEdit(self.frame_4_envelope)
        self.lineEdit_time_envelope.setGeometry(QtCore.QRect(80, 40, 111, 21))
        self.lineEdit_time_envelope.setTabletTracking(False)
        self.lineEdit_time_envelope.setObjectName("lineEdit_time_envelope")
        self.pushButton_setup_parameters_envelope = QtWidgets.QPushButton(self.frame_4_envelope)
        self.pushButton_setup_parameters_envelope.setGeometry(QtCore.QRect(80, 160, 113, 32))
        self.pushButton_setup_parameters_envelope.setObjectName("pushButton_setup_parameters_envelope")
        self.checkBox_normalize_envelope = QtWidgets.QCheckBox(self.frame_4_envelope)
        self.checkBox_normalize_envelope.setGeometry(QtCore.QRect(80, 100, 111, 20))
        self.checkBox_normalize_envelope.setObjectName("checkBox_normalize_envelope")
        self.pushButton_export_envelope = QtWidgets.QPushButton(self.frame_4_envelope)
        self.pushButton_export_envelope.setGeometry(QtCore.QRect(40, 320, 121, 31))
        self.pushButton_export_envelope.setObjectName("pushButton_export_envelope")
        self.lineEdit_freq1_envelope = QtWidgets.QLineEdit(self.frame_4_envelope)
        self.lineEdit_freq1_envelope.setGeometry(QtCore.QRect(80, 130, 51, 21))
        self.lineEdit_freq1_envelope.setObjectName("lineEdit_freq1_envelope")
        self.label_2_envelope = QtWidgets.QLabel(self.frame_4_envelope)
        self.label_2_envelope.setGeometry(QtCore.QRect(10, 70, 59, 16))
        self.label_2_envelope.setObjectName("label_2_envelope")
        self.lineEdit_fs_envelope = QtWidgets.QLineEdit(self.frame_4_envelope)
        self.lineEdit_fs_envelope.setGeometry(QtCore.QRect(80, 10, 51, 21))
        self.lineEdit_fs_envelope.setObjectName("lineEdit_fs_envelope")
        self.frame_5_envelope = QtWidgets.QFrame(self.frame_3_envelope)
        self.frame_5_envelope.setGeometry(QtCore.QRect(240, 10, 511, 361))
        self.frame_5_envelope.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5_envelope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5_envelope.setObjectName("frame_5_envelope")
        self.MplWidget_2 = MplWidget(self.frame_5_envelope)
        self.MplWidget_2.setGeometry(QtCore.QRect(20, 10, 480, 331))
        self.MplWidget_2.setMinimumSize(QtCore.QSize(480, 320))
        self.MplWidget_2.setObjectName("MplWidget_2")
        MainWindow.setCentralWidget(self.centralwidget_envelope)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Envelope Filter</span></p></body></html>"))
        self.label_3_envelope.setText(_translate("MainWindow", "Freq"))
        self.label_envelope.setText(_translate("MainWindow", "Minute"))
        self.lineEdit_freq2_envelope.setText(_translate("MainWindow", "24"))
        self.pushButton_test_envelope.setText(_translate("MainWindow", "test"))
        self.label_4_envelope.setText(_translate("MainWindow", "Fs"))
        self.lineEdit_ch_envelope.setText(_translate("MainWindow", "0-2120"))
        self.lineEdit_time_envelope.setText(_translate("MainWindow", "0"))
        self.pushButton_setup_parameters_envelope.setText(_translate("MainWindow", "Confirm"))
        self.checkBox_normalize_envelope.setText(_translate("MainWindow", "Normalization"))
        self.pushButton_export_envelope.setText(_translate("MainWindow", "Export"))
        self.lineEdit_freq1_envelope.setText(_translate("MainWindow", "0.5"))
        self.label_2_envelope.setText(_translate("MainWindow", "Channel"))
        self.lineEdit_fs_envelope.setText(_translate("MainWindow", "500"))
from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_envelope = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_envelope()
    ui.setupUi(MainWindow_envelope)
    MainWindow_envelope.show()
    sys.exit(app.exec_())