# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadingWindow(object):

    
    def setupUi(self, LoadingWindow):
        LoadingWindow.setObjectName("LoadingWindow")
        LoadingWindow.resize(878, 637)
        LoadingWindow.setStyleSheet("\n"
"\n"
"QMainWindow{\n"
"background: rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(LoadingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(831, 441))
        self.frame.setMaximumSize(QtCore.QSize(831, 500))
        self.frame.setStyleSheet("QFrame{background: rgb(55, 113, 233);}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setMinimumSize(QtCore.QSize(805, 57))
        self.frame_11.setMaximumSize(QtCore.QSize(805, 100))
        self.frame_11.setStyleSheet("QFrame{\n"
"background: #F5FAFE;\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout.setObjectName("gridLayout")
        self.label_27 = QtWidgets.QLabel(self.frame_11)
        self.label_27.setMinimumSize(QtCore.QSize(386, 16))
        self.label_27.setMaximumSize(QtCore.QSize(386, 16))
        self.label_27.setStyleSheet("QLabel{\n"
"color: rgb(16, 19, 7);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"}")
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 0, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_11)
        self.comboBox_5.setMaximumSize(QtCore.QSize(103, 32))
        self.comboBox_5.setStyleSheet("QComboBox{\n"
"color: black;\n"
"}")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout.addWidget(self.comboBox_5, 0, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_11, clicked = lambda: self.get_file_format())
        self.pushButton.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.frame_11, 6, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setMinimumSize(QtCore.QSize(805, 57))
        self.frame_5.setMaximumSize(QtCore.QSize(805, 57))
        self.frame_5.setStyleSheet("QFrame{\n"
"background: #F5FAFE;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_21 = QtWidgets.QLabel(self.frame_5)
        self.label_21.setMinimumSize(QtCore.QSize(646, 15))
        self.label_21.setMaximumSize(QtCore.QSize(646, 15))
        self.label_21.setStyleSheet("QLabel{\n"
"color: rgb(16, 19, 7);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"}")
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_channel = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_channel.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}")
        self.lineEdit_channel.setObjectName("lineEdit_channel")
        self.gridLayout_4.addWidget(self.lineEdit_channel, 0, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_5, 4, 0, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.frame)
        self.frame_10.setMinimumSize(QtCore.QSize(805, 57))
        self.frame_10.setMaximumSize(QtCore.QSize(805, 57))
        self.frame_10.setStyleSheet("QFrame{\n"
"background: #F5FAFE;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_23 = QtWidgets.QLabel(self.frame_10)
        self.label_23.setStyleSheet("QLabel{\n"
"color: rgb(16, 19, 7);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"}")
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_10)
        self.comboBox.setStyleSheet("QComboBox{\n"
"color: black;\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_3.addWidget(self.comboBox, 0, 1, 1, 1)
        self.pushButtoncombo_2 = QtWidgets.QPushButton(self.frame_10, self.get_sysname())
        self.pushButtoncombo_2.setStyleSheet("QPushButton{\n"
"color:black;\n"
"}")
        self.pushButtoncombo_2.setObjectName("pushButtoncombo_2")
        self.gridLayout_3.addWidget(self.pushButtoncombo_2, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.frame_10, 5, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setMinimumSize(QtCore.QSize(805, 57))
        self.frame_4.setMaximumSize(QtCore.QSize(805, 57))
        self.frame_4.setStyleSheet("QFrame{\n"
"background: #F5FAFE;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(16, 19, 7);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_4)
        self.label_14.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 1, 1, 1)
        self.lineEdit_etime_1 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_etime_1.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_etime_1.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_etime_1.setObjectName("lineEdit_etime_1")
        self.gridLayout_6.addWidget(self.lineEdit_etime_1, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_4)
        self.label_15.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_15.setObjectName("label_15")
        self.gridLayout_6.addWidget(self.label_15, 0, 3, 1, 1)
        self.lineEdit_etime_2 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_etime_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_etime_2.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_etime_2.setObjectName("lineEdit_etime_2")
        self.gridLayout_6.addWidget(self.lineEdit_etime_2, 0, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.label_16, 0, 5, 1, 1)
        self.lineEdit_etime_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_etime_3.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_etime_3.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_etime_3.setObjectName("lineEdit_etime_3")
        self.gridLayout_6.addWidget(self.lineEdit_etime_3, 0, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 7, 1, 1)
        self.lineEdit_etime_4 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_etime_4.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_etime_4.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_etime_4.setObjectName("lineEdit_etime_4")
        self.gridLayout_6.addWidget(self.lineEdit_etime_4, 0, 8, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_4)
        self.label_18.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 0, 9, 1, 1)
        self.lineEdit_etime_5 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_etime_5.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_etime_5.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_etime_5.setObjectName("lineEdit_etime_5")
        self.gridLayout_6.addWidget(self.lineEdit_etime_5, 0, 10, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 0, 11, 1, 1)
        self.lineEdit_etime_6 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_etime_6.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_etime_6.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_etime_6.setObjectName("lineEdit_etime_6")
        self.gridLayout_6.addWidget(self.lineEdit_etime_6, 0, 12, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.frame_4)
        self.label_20.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 0, 13, 1, 1)
        self.lineEdit_etime_7 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_etime_7.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_etime_7.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_etime_7.setObjectName("lineEdit_etime_7")
        self.gridLayout_6.addWidget(self.lineEdit_etime_7, 0, 14, 1, 1)
        self.gridLayout_9.addWidget(self.frame_4, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(447, 67))
        self.frame_2.setMaximumSize(QtCore.QSize(447, 67))
        self.frame_2.setStyleSheet("QFrame{\n"
"border: None;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_save = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_save.setMinimumSize(QtCore.QSize(131, 41))
        self.pushButton_save.setMaximumSize(QtCore.QSize(131, 41))
        self.pushButton_save.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_2.addWidget(self.pushButton_save, 0, 2, 1, 1)
        self.pushButton_2ndwindow = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2ndwindow.setMinimumSize(QtCore.QSize(131, 41))
        self.pushButton_2ndwindow.setMaximumSize(QtCore.QSize(131, 41))
        self.pushButton_2ndwindow.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_2ndwindow.setObjectName("pushButton_2ndwindow")
        self.gridLayout_2.addWidget(self.pushButton_2ndwindow, 0, 1, 1, 1)
        self.pushButton_start = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_start.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_start.setMaximumSize(QtCore.QSize(131, 41))
        self.pushButton_start.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.gridLayout_2.addWidget(self.pushButton_start, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_2, 9, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setMinimumSize(QtCore.QSize(805, 57))
        self.frame_9.setMaximumSize(QtCore.QSize(805, 57))
        self.frame_9.setStyleSheet("QFrame{\n"
"background: #F5FAFE;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setMinimumSize(QtCore.QSize(690, 16))
        self.label_22.setMaximumSize(QtCore.QSize(690, 16))
        self.label_22.setStyleSheet("QLabel{\n"
"color: rgb(16, 19, 7);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"}")
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 0, 0, 2, 2)
        self.lineEdit_fs = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_fs.setMinimumSize(QtCore.QSize(81, 21))
        self.lineEdit_fs.setMaximumSize(QtCore.QSize(81, 21))
        self.lineEdit_fs.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}")
        self.lineEdit_fs.setObjectName("lineEdit_fs")
        self.gridLayout_5.addWidget(self.lineEdit_fs, 1, 1, 1, 1)
        self.gridLayout_9.addWidget(self.frame_9, 3, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(805, 57))
        self.frame_3.setMaximumSize(QtCore.QSize(805, 57))
        self.frame_3.setStyleSheet("QFrame{\n"
"background: #F5FAFE;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setStyleSheet("QLabel{\n"
"color: rgb(16, 19, 7);\n"
"font-weight: bold;\n"
"font-size: 16px;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 1, 1, 1)
        self.lineEdit_stime_1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_stime_1.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_stime_1.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_stime_1.setObjectName("lineEdit_stime_1")
        self.gridLayout_7.addWidget(self.lineEdit_stime_1, 0, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 3, 1, 1)
        self.lineEdit_stime_2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_stime_2.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_stime_2.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_stime_2.setObjectName("lineEdit_stime_2")
        self.gridLayout_7.addWidget(self.lineEdit_stime_2, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 5, 1, 1)
        self.lineEdit_stime_3 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_stime_3.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_stime_3.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_stime_3.setObjectName("lineEdit_stime_3")
        self.gridLayout_7.addWidget(self.lineEdit_stime_3, 0, 6, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.gridLayout_7.addWidget(self.label_10, 0, 7, 1, 1)
        self.lineEdit_stime_4 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_stime_4.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_stime_4.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_stime_4.setObjectName("lineEdit_stime_4")
        self.gridLayout_7.addWidget(self.lineEdit_stime_4, 0, 8, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 9, 1, 1)
        self.lineEdit_stime_5 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_stime_5.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_stime_5.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_stime_5.setObjectName("lineEdit_stime_5")
        self.gridLayout_7.addWidget(self.lineEdit_stime_5, 0, 10, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 0, 11, 1, 1)
        self.lineEdit_stime_6 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_stime_6.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_stime_6.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_stime_6.setObjectName("lineEdit_stime_6")
        self.gridLayout_7.addWidget(self.lineEdit_stime_6, 0, 12, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setStyleSheet("QLabel{\n"
"color: black;\n"
"}")
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 0, 13, 1, 1)
        self.lineEdit_stime_7 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_stime_7.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_stime_7.setStyleSheet("QLineEdit{\n"
"background: rgb(255,255,255);\n"
"color: rgb(11, 7, 4);\n"
"}\n"
"")
        self.lineEdit_stime_7.setObjectName("lineEdit_stime_7")
        self.gridLayout_7.addWidget(self.lineEdit_stime_7, 0, 14, 1, 1)
        self.gridLayout_9.addWidget(self.frame_3, 1, 0, 1, 1)
        self.pushButton_getmat = QtWidgets.QPushButton(self.frame)
        self.pushButton_getmat.setMinimumSize(QtCore.QSize(116, 31))
        self.pushButton_getmat.setMaximumSize(QtCore.QSize(103, 31))
        self.pushButton_getmat.setStyleSheet("pushButton_getmat{\n"
"color:#FFFFFF;\n"
"border: None;\n"
"}")
        self.pushButton_getmat.setText("")
        self.pushButton_getmat.setObjectName("pushButton_getmat")
        self.gridLayout_9.addWidget(self.pushButton_getmat, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame, 0, 0, 1, 1)
        LoadingWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoadingWindow)
        self.statusbar.setObjectName("statusbar")
        LoadingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoadingWindow)
        QtCore.QMetaObject.connectSlotsByName(LoadingWindow)

    def retranslateUi(self, LoadingWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadingWindow.setWindowTitle(_translate("LoadingWindow", "MainWindow"))
        self.label_27.setText(_translate("LoadingWindow", "File Format"))
        self.comboBox_5.setItemText(0, _translate("LoadingWindow", "h5"))
        self.comboBox_5.setItemText(1, _translate("LoadingWindow", "tdms"))
        self.pushButton.setText(_translate("LoadingWindow", "Confirm"))
        self.label_21.setText(_translate("LoadingWindow", "Channels "))
        self.lineEdit_channel.setText(_translate("LoadingWindow", "0-2432"))
        self.label_23.setText(_translate("LoadingWindow", "System Name"))
        self.comboBox.setItemText(0, _translate("LoadingWindow", "PSU DAS DATA"))
        self.comboBox.setItemText(1, _translate("LoadingWindow", "Pittsburgh DAS DATA"))
        self.pushButtoncombo_2.setText(_translate("LoadingWindow", "Confirm"))
        self.label_2.setText(_translate("LoadingWindow", "End Time "))
        self.label_14.setText(_translate("LoadingWindow", "Year"))
        self.lineEdit_etime_1.setText(_translate("LoadingWindow", "2021"))
        self.label_15.setText(_translate("LoadingWindow", "Month"))
        self.lineEdit_etime_2.setText(_translate("LoadingWindow", "8"))
        self.label_16.setText(_translate("LoadingWindow", "Day"))
        self.lineEdit_etime_3.setText(_translate("LoadingWindow", "18"))
        self.label_17.setText(_translate("LoadingWindow", "Hour"))
        self.lineEdit_etime_4.setText(_translate("LoadingWindow", "16"))
        self.label_18.setText(_translate("LoadingWindow", "min"))
        self.lineEdit_etime_5.setText(_translate("LoadingWindow", "22"))
        self.label_19.setText(_translate("LoadingWindow", "sec"))
        self.lineEdit_etime_6.setText(_translate("LoadingWindow", "36"))
        self.label_20.setText(_translate("LoadingWindow", "ms"))
        self.lineEdit_etime_7.setText(_translate("LoadingWindow", "895"))
        self.pushButton_save.setText(_translate("LoadingWindow", "Save"))
        self.pushButton_2ndwindow.setText(_translate("LoadingWindow", "Load Data"))
        self.pushButton_start.setText(_translate("LoadingWindow", "Import"))
        self.label_22.setText(_translate("LoadingWindow", "Sampling Rate"))
        self.lineEdit_fs.setText(_translate("LoadingWindow", "50"))
        self.label_5.setText(_translate("LoadingWindow", "Start Time"))
        self.label_7.setText(_translate("LoadingWindow", "Year"))
        self.lineEdit_stime_1.setText(_translate("LoadingWindow", "2021"))
        self.label_8.setText(_translate("LoadingWindow", "Month"))
        self.lineEdit_stime_2.setText(_translate("LoadingWindow", "8"))
        self.label_9.setText(_translate("LoadingWindow", "Day"))
        self.lineEdit_stime_3.setText(_translate("LoadingWindow", "18"))
        self.label_10.setText(_translate("LoadingWindow", "Hour"))
        self.lineEdit_stime_4.setText(_translate("LoadingWindow", "16"))
        self.label_11.setText(_translate("LoadingWindow", "min"))
        self.lineEdit_stime_5.setText(_translate("LoadingWindow", "20"))
        self.label_12.setText(_translate("LoadingWindow", "sec"))
        self.lineEdit_stime_6.setText(_translate("LoadingWindow", "36"))
        self.label_13.setText(_translate("LoadingWindow", "ms"))
        self.lineEdit_stime_7.setText(_translate("LoadingWindow", "895"))
