# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lowpass.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_Lowpass(object):
    def setupUi(self, MainWindow_Lowpass):
        MainWindow_Lowpass.setObjectName("MainWindow_Lowpass")
        MainWindow_Lowpass.resize(800, 600)
        self.centralwidget_Lowpass = QtWidgets.QWidget(MainWindow_Lowpass)
        self.centralwidget_Lowpass.setObjectName("centralwidget_Lowpass")
        self.frame_Lowpass = QtWidgets.QFrame(self.centralwidget_Lowpass)
        self.frame_Lowpass.setGeometry(QtCore.QRect(0, 10, 791, 471))
        self.frame_Lowpass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Lowpass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Lowpass.setObjectName("frame_Lowpass")
        self.frame_2_Lowpass = QtWidgets.QFrame(self.frame_Lowpass)
        self.frame_2_Lowpass.setGeometry(QtCore.QRect(240, 20, 301, 41))
        self.frame_2_Lowpass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_Lowpass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_Lowpass.setObjectName("frame_2_Lowpass")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.frame_2_Lowpass)
        self.textBrowser_2.setGeometry(QtCore.QRect(0, 0, 301, 41))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.frame_8_Lowpass = QtWidgets.QFrame(self.frame_Lowpass)
        self.frame_8_Lowpass.setGeometry(QtCore.QRect(10, 90, 761, 381))
        self.frame_8_Lowpass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8_Lowpass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8_Lowpass.setObjectName("frame_8_Lowpass")
        self.frame_7_Lowpass = QtWidgets.QFrame(self.frame_8_Lowpass)
        self.frame_7_Lowpass.setGeometry(QtCore.QRect(10, 10, 221, 361))
        self.frame_7_Lowpass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7_Lowpass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7_Lowpass.setObjectName("frame_7_Lowpass")
        self.label_3_Lowpass = QtWidgets.QLabel(self.frame_7_Lowpass)
        self.label_3_Lowpass.setGeometry(QtCore.QRect(10, 120, 59, 16))
        self.label_3_Lowpass.setObjectName("label_3_Lowpass")
        self.label_Lowpass = QtWidgets.QLabel(self.frame_7_Lowpass)
        self.label_Lowpass.setGeometry(QtCore.QRect(10, 40, 59, 16))
        self.label_Lowpass.setObjectName("label_Lowpass")
        self.lineEdit_freq2_Lowpass = QtWidgets.QLineEdit(self.frame_7_Lowpass)
        self.lineEdit_freq2_Lowpass.setGeometry(QtCore.QRect(140, 120, 51, 21))
        self.lineEdit_freq2_Lowpass.setObjectName("lineEdit_freq2_Lowpass")
        self.pushButton_test_Lowpass = QtWidgets.QPushButton(self.frame_7_Lowpass)
        self.pushButton_test_Lowpass.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.pushButton_test_Lowpass.setObjectName("pushButton_test_Lowpass")
        self.label_4_Lowpass = QtWidgets.QLabel(self.frame_7_Lowpass)
        self.label_4_Lowpass.setGeometry(QtCore.QRect(20, 10, 59, 16))
        self.label_4_Lowpass.setObjectName("label_4_Lowpass")
        self.lineEdit_ch_Lowpass = QtWidgets.QLineEdit(self.frame_7_Lowpass)
        self.lineEdit_ch_Lowpass.setGeometry(QtCore.QRect(80, 70, 111, 21))
        self.lineEdit_ch_Lowpass.setObjectName("lineEdit_ch_Lowpass")
        self.lineEdit_time_Lowpass = QtWidgets.QLineEdit(self.frame_7_Lowpass)
        self.lineEdit_time_Lowpass.setGeometry(QtCore.QRect(80, 40, 111, 21))
        self.lineEdit_time_Lowpass.setTabletTracking(False)
        self.lineEdit_time_Lowpass.setObjectName("lineEdit_time_Lowpass")
        self.pushButton_setup_parameters_Lowpass = QtWidgets.QPushButton(self.frame_7_Lowpass)
        self.pushButton_setup_parameters_Lowpass.setGeometry(QtCore.QRect(80, 160, 113, 32))
        self.pushButton_setup_parameters_Lowpass.setObjectName("pushButton_setup_parameters_Lowpass")
        self.checkBox_normalize_Lowpass = QtWidgets.QCheckBox(self.frame_7_Lowpass)
        self.checkBox_normalize_Lowpass.setGeometry(QtCore.QRect(80, 90, 111, 20))
        self.checkBox_normalize_Lowpass.setObjectName("checkBox_normalize_Lowpass")
        self.pushButton_export_Lowpass = QtWidgets.QPushButton(self.frame_7_Lowpass)
        self.pushButton_export_Lowpass.setGeometry(QtCore.QRect(40, 320, 121, 31))
        self.pushButton_export_Lowpass.setObjectName("pushButton_export_Lowpass")
        self.lineEdit_freq1_Lowpass = QtWidgets.QLineEdit(self.frame_7_Lowpass)
        self.lineEdit_freq1_Lowpass.setGeometry(QtCore.QRect(80, 120, 51, 21))
        self.lineEdit_freq1_Lowpass.setObjectName("lineEdit_freq1_Lowpass")
        self.label_2_Lowpass = QtWidgets.QLabel(self.frame_7_Lowpass)
        self.label_2_Lowpass.setGeometry(QtCore.QRect(10, 70, 59, 16))
        self.label_2_Lowpass.setObjectName("label_2_Lowpass")
        self.lineEdit_fs_Lowpass = QtWidgets.QLineEdit(self.frame_7_Lowpass)
        self.lineEdit_fs_Lowpass.setGeometry(QtCore.QRect(80, 10, 51, 21))
        self.lineEdit_fs_Lowpass.setObjectName("lineEdit_fs_Lowpass")
        self.frame_5_Lowpass = QtWidgets.QFrame(self.frame_8_Lowpass)
        self.frame_5_Lowpass.setGeometry(QtCore.QRect(240, 10, 511, 361))
        self.frame_5_Lowpass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5_Lowpass.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5_Lowpass.setObjectName("frame_5_Lowpass")
        self.MplWidget_4_Lowpass = MplWidget(self.frame_5_Lowpass)
        self.MplWidget_4_Lowpass.setGeometry(QtCore.QRect(20, 10, 480, 331))
        self.MplWidget_4_Lowpass.setMinimumSize(QtCore.QSize(480, 320))
        self.MplWidget_4_Lowpass.setObjectName("MplWidget_4_Lowpass")
        MainWindow_Lowpass.setCentralWidget(self.centralwidget_Lowpass)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_Lowpass)
        self.statusbar.setObjectName("statusbar")
        MainWindow_Lowpass.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_Lowpass)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_Lowpass)

    def retranslateUi(self, MainWindow_Lowpass):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_Lowpass.setWindowTitle(_translate("MainWindow_Lowpass", "MainWindow"))
        self.textBrowser_2.setHtml(_translate("MainWindow_Lowpass", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Lowpass Filter</span></p></body></html>"))
        self.label_3_Lowpass.setText(_translate("MainWindow_Lowpass", "Freq"))
        self.label_Lowpass.setText(_translate("MainWindow_Lowpass", "Minute"))
        self.lineEdit_freq2_Lowpass.setText(_translate("MainWindow_Lowpass", "24"))
        self.pushButton_test_Lowpass.setText(_translate("MainWindow_Lowpass", "test"))
        self.label_4_Lowpass.setText(_translate("MainWindow_Lowpass", "Fs"))
        self.lineEdit_ch_Lowpass.setText(_translate("MainWindow_Lowpass", "0-2120"))
        self.lineEdit_time_Lowpass.setText(_translate("MainWindow_Lowpass", "0"))
        self.pushButton_setup_parameters_Lowpass.setText(_translate("MainWindow_Lowpass", "Confirm"))
        self.checkBox_normalize_Lowpass.setText(_translate("MainWindow_Lowpass", "Normalization"))
        self.pushButton_export_Lowpass.setText(_translate("MainWindow_Lowpass", "Export"))
        self.lineEdit_freq1_Lowpass.setText(_translate("MainWindow_Lowpass", "0.5"))
        self.label_2_Lowpass.setText(_translate("MainWindow_Lowpass", "Channel"))
        self.lineEdit_fs_Lowpass.setText(_translate("MainWindow_Lowpass", "500"))
from mplwidget import MplWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_Lowpass = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_Lowpass()
    ui.setupUi(MainWindow_Lowpass)
    MainWindow_Lowpass.show()
    sys.exit(app.exec_())