# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lowpass_cheby_.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_LowpassCheby(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget_LowpassCheby = QtWidgets.QWidget(MainWindow)
        self.centralwidget_LowpassCheby.setObjectName("centralwidget_LowpassCheby")
        self.frame_LowpassCheby = QtWidgets.QFrame(self.centralwidget_LowpassCheby)
        self.frame_LowpassCheby.setGeometry(QtCore.QRect(0, 10, 791, 471))
        self.frame_LowpassCheby.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_LowpassCheby.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LowpassCheby.setObjectName("frame_LowpassCheby")
        self.frame_2_LowpassCheby = QtWidgets.QFrame(self.frame_LowpassCheby)
        self.frame_2_LowpassCheby.setGeometry(QtCore.QRect(240, 20, 301, 41))
        self.frame_2_LowpassCheby.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_LowpassCheby.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_LowpassCheby.setObjectName("frame_2_LowpassCheby")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2_LowpassCheby)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 301, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.frame_3_LowpassCheby = QtWidgets.QFrame(self.frame_LowpassCheby)
        self.frame_3_LowpassCheby.setGeometry(QtCore.QRect(10, 90, 761, 381))
        self.frame_3_LowpassCheby.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_LowpassCheby.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_LowpassCheby.setObjectName("frame_3_LowpassCheby")
        self.frame_4_LowpassCheby = QtWidgets.QFrame(self.frame_3_LowpassCheby)
        self.frame_4_LowpassCheby.setGeometry(QtCore.QRect(10, 10, 221, 361))
        self.frame_4_LowpassCheby.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4_LowpassCheby.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4_LowpassCheby.setObjectName("frame_4_LowpassCheby")
        self.label_3_LowpassCheby = QtWidgets.QLabel(self.frame_4_LowpassCheby)
        self.label_3_LowpassCheby.setGeometry(QtCore.QRect(10, 120, 59, 16))
        self.label_3_LowpassCheby.setObjectName("label_3_LowpassCheby")
        self.label_LowpassCheby = QtWidgets.QLabel(self.frame_4_LowpassCheby)
        self.label_LowpassCheby.setGeometry(QtCore.QRect(10, 40, 59, 16))
        self.label_LowpassCheby.setObjectName("label_LowpassCheby")
        self.lineEdit_freq2_LowpassCheby = QtWidgets.QLineEdit(self.frame_4_LowpassCheby)
        self.lineEdit_freq2_LowpassCheby.setGeometry(QtCore.QRect(140, 120, 51, 21))
        self.lineEdit_freq2_LowpassCheby.setObjectName("lineEdit_freq2_LowpassCheby")
        self.pushButton_test_LowpassCheby = QtWidgets.QPushButton(self.frame_4_LowpassCheby)
        self.pushButton_test_LowpassCheby.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.pushButton_test_LowpassCheby.setObjectName("pushButton_test_LowpassCheby")
        self.label_4_LowpassCheby = QtWidgets.QLabel(self.frame_4_LowpassCheby)
        self.label_4_LowpassCheby.setGeometry(QtCore.QRect(20, 10, 59, 16))
        self.label_4_LowpassCheby.setObjectName("label_4_LowpassCheby")
        self.lineEdit_ch_LowpassCheby = QtWidgets.QLineEdit(self.frame_4_LowpassCheby)
        self.lineEdit_ch_LowpassCheby.setGeometry(QtCore.QRect(80, 70, 111, 21))
        self.lineEdit_ch_LowpassCheby.setObjectName("lineEdit_ch_LowpassCheby")
        self.lineEdit_time_LowpassCheby = QtWidgets.QLineEdit(self.frame_4_LowpassCheby)
        self.lineEdit_time_LowpassCheby.setGeometry(QtCore.QRect(80, 40, 111, 21))
        self.lineEdit_time_LowpassCheby.setTabletTracking(False)
        self.lineEdit_time_LowpassCheby.setObjectName("lineEdit_time_LowpassCheby")
        self.pushButton_setup_parameters_LowpassCheby = QtWidgets.QPushButton(self.frame_4_LowpassCheby)
        self.pushButton_setup_parameters_LowpassCheby.setGeometry(QtCore.QRect(80, 150, 113, 32))
        self.pushButton_setup_parameters_LowpassCheby.setObjectName("pushButton_setup_parameters_LowpassCheby")
        self.checkBox_normalize_LowpassCheby = QtWidgets.QCheckBox(self.frame_4_LowpassCheby)
        self.checkBox_normalize_LowpassCheby.setGeometry(QtCore.QRect(80, 90, 111, 20))
        self.checkBox_normalize_LowpassCheby.setObjectName("checkBox_normalize_LowpassCheby")
        self.pushButton_export_LowpassCheby = QtWidgets.QPushButton(self.frame_4_LowpassCheby)
        self.pushButton_export_LowpassCheby.setGeometry(QtCore.QRect(40, 320, 121, 31))
        self.pushButton_export_LowpassCheby.setObjectName("pushButton_export_LowpassCheby")
        self.lineEdit_freq1_LowpassCheby = QtWidgets.QLineEdit(self.frame_4_LowpassCheby)
        self.lineEdit_freq1_LowpassCheby.setGeometry(QtCore.QRect(80, 120, 51, 21))
        self.lineEdit_freq1_LowpassCheby.setObjectName("lineEdit_freq1_LowpassCheby")
        self.label_2_LowpassCheby = QtWidgets.QLabel(self.frame_4_LowpassCheby)
        self.label_2_LowpassCheby.setGeometry(QtCore.QRect(10, 70, 59, 16))
        self.label_2_LowpassCheby.setObjectName("label_2_LowpassCheby")
        self.lineEdit_fs_LowpassCheby = QtWidgets.QLineEdit(self.frame_4_LowpassCheby)
        self.lineEdit_fs_LowpassCheby.setGeometry(QtCore.QRect(80, 10, 51, 21))
        self.lineEdit_fs_LowpassCheby.setObjectName("lineEdit_fs_LowpassCheby")
        self.frame_5_LowpassCheby = QtWidgets.QFrame(self.frame_3_LowpassCheby)
        self.frame_5_LowpassCheby.setGeometry(QtCore.QRect(240, 10, 511, 361))
        self.frame_5_LowpassCheby.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5_LowpassCheby.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5_LowpassCheby.setObjectName("frame_5_LowpassCheby")
        self.MplWidget_2_LowpassCheby = MplWidget(self.frame_5_LowpassCheby)
        self.MplWidget_2_LowpassCheby.setGeometry(QtCore.QRect(20, 10, 480, 331))
        self.MplWidget_2_LowpassCheby.setMinimumSize(QtCore.QSize(480, 320))
        self.MplWidget_2_LowpassCheby.setObjectName("MplWidget_2_LowpassCheby")
        MainWindow.setCentralWidget(self.centralwidget_LowpassCheby)
        self.statusbar_LowpassCheby = QtWidgets.QStatusBar(MainWindow)
        self.statusbar_LowpassCheby.setObjectName("statusbar_LowpassCheby")
        MainWindow.setStatusBar(self.statusbar_LowpassCheby)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt;\">Lowpass Cheby</span></p></body></html>"))
        self.label_3_LowpassCheby.setText(_translate("MainWindow", "Freq"))
        self.label_LowpassCheby.setText(_translate("MainWindow", "Minute"))
        self.lineEdit_freq2_LowpassCheby.setText(_translate("MainWindow", "24"))
        self.pushButton_test_LowpassCheby.setText(_translate("MainWindow", "test"))
        self.label_4_LowpassCheby.setText(_translate("MainWindow", "Fs"))
        self.lineEdit_ch_LowpassCheby.setText(_translate("MainWindow", "0-2120"))
        self.lineEdit_time_LowpassCheby.setText(_translate("MainWindow", "0"))
        self.pushButton_setup_parameters_LowpassCheby.setText(_translate("MainWindow", "Confirm"))
        self.checkBox_normalize_LowpassCheby.setText(_translate("MainWindow", "Normalization"))
        self.pushButton_export_LowpassCheby.setText(_translate("MainWindow", "Export"))
        self.lineEdit_freq1_LowpassCheby.setText(_translate("MainWindow", "0.5"))
        self.label_2_LowpassCheby.setText(_translate("MainWindow", "Channel"))
        self.lineEdit_fs_LowpassCheby.setText(_translate("MainWindow", "500"))
from mplwidget import MplWidget



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_LowpassCheby = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_LowpassCheby()
    ui.setupUi(MainWindow_LowpassCheby)
    MainWindow_LowpassCheby.show()
    sys.exit(app.exec_())