# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpeningWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from main import Mymain

class Ui_MainWindow(object):
    
    def openLoadDataWindow(self):
        app = QtWidgets.QApplication([])  # Create a Qt application
        window = Mymain()  # Create an instance of Mymain
        window.show()  # Show the main window
        app.exec_()  # Start the event loop
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 684)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_name_widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_name_widget.sizePolicy().hasHeightForWidth())
        self.icon_name_widget.setSizePolicy(sizePolicy)
        self.icon_name_widget.setStyleSheet("\n"
"\n"
"QWidget{\n"
"background: rgb(55, 113, 233);\n"
"}\n"
"\n"
"QPushButton{\n"
"color:black;\n"
"text-align: left;\n"
"height : 30 px;\n"
"border: None;\n"
"padding-left: 10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color: #F5FAFE;\n"
"color: #1F95EF;\n"
"font-weight: bold;\n"
"\n"
"}\n"
"")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_2.setContentsMargins(15, 50, 25, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.icon_name_widget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setHandleWidth(15)
        self.splitter_2.setObjectName("splitter_2")
        self.HomeButton_2 = QtWidgets.QPushButton(self.splitter_2)
        self.HomeButton_2.setMaximumSize(QtCore.QSize(102, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("GUI Icons/home-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HomeButton_2.setIcon(icon)
        self.HomeButton_2.setIconSize(QtCore.QSize(20, 20))
        self.HomeButton_2.setCheckable(True)
        self.HomeButton_2.setAutoExclusive(True)
        self.HomeButton_2.setObjectName("HomeButton_2")
        self.LoadDataButton_2 = QtWidgets.QPushButton(self.splitter_2)
        self.LoadDataButton_2.setMaximumSize(QtCore.QSize(102, 30))
        self.LoadDataButton_2.setStyleSheet("pussButton_9{\n"
"padding-right:10px\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("GUI Icons/data-copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LoadDataButton_2.setIcon(icon1)
        self.LoadDataButton_2.setIconSize(QtCore.QSize(20, 20))
        self.LoadDataButton_2.setCheckable(True)
        self.LoadDataButton_2.setAutoExclusive(True)
        self.LoadDataButton_2.setObjectName("LoadDataButton_2")
        self.SearchButton_2 = QtWidgets.QPushButton(self.splitter_2)
        self.SearchButton_2.setMinimumSize(QtCore.QSize(102, 0))
        self.SearchButton_2.setMaximumSize(QtCore.QSize(102, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("GUI Icons/magnifying-glass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SearchButton_2.setIcon(icon2)
        self.SearchButton_2.setIconSize(QtCore.QSize(20, 20))
        self.SearchButton_2.setCheckable(True)
        self.SearchButton_2.setAutoExclusive(True)
        self.SearchButton_2.setObjectName("SearchButton_2")
        self.verticalLayout_2.addWidget(self.splitter_2)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.MoreInfoButton_2 = QtWidgets.QPushButton(self.icon_name_widget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("GUI Icons/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MoreInfoButton_2.setIcon(icon3)
        self.MoreInfoButton_2.setIconSize(QtCore.QSize(20, 20))
        self.MoreInfoButton_2.setCheckable(True)
        self.MoreInfoButton_2.setAutoExclusive(True)
        self.MoreInfoButton_2.setObjectName("MoreInfoButton_2")
        self.verticalLayout_2.addWidget(self.MoreInfoButton_2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.Main_menu = QtWidgets.QWidget(self.centralwidget)
        self.Main_menu.setObjectName("Main_menu")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Main_menu)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.Main_menu)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MenuButton = QtWidgets.QPushButton(self.widget)
        self.MenuButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("GUI Icons/burger-bar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MenuButton.setIcon(icon4)
        self.MenuButton.setIconSize(QtCore.QSize(23, 23))
        self.MenuButton.setCheckable(True)
        self.MenuButton.setObjectName("MenuButton")
        self.horizontalLayout.addWidget(self.MenuButton)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(24)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.Header_Widget = QtWidgets.QStackedWidget(self.Main_menu)
        self.Header_Widget.setStyleSheet("\n"
"QStackedWidget{\n"
"background: rgb(255, 255, 255);\n"
"}")
        self.Header_Widget.setObjectName("Header_Widget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.textBrowser = QtWidgets.QTextBrowser(self.page)
        self.textBrowser.setGeometry(QtCore.QRect(270, 130, 256, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.Header_Widget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.page_3)
        self.textBrowser_3.setGeometry(QtCore.QRect(250, 140, 256, 192))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.Header_Widget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.page_4)
        self.textBrowser_4.setGeometry(QtCore.QRect(300, 160, 256, 192))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.Header_Widget.addWidget(self.page_4)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setMaximumSize(QtCore.QSize(701, 461))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMaximumSize(QtCore.QSize(551, 341))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../Image 8-12-24 at 12.43 AM.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.pushButton_LoadData = QtWidgets.QPushButton(self.frame, clicked = lambda: self.openLoadDataWindow())
        self.pushButton_LoadData.setMaximumSize(QtCore.QSize(141, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(True)
        self.pushButton_LoadData.setFont(font)
        self.pushButton_LoadData.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #0276FF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_LoadData.setObjectName("pushButton_LoadData")
        self.gridLayout_3.addWidget(self.pushButton_LoadData, 1, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 0, 0, 1, 1)
        self.Header_Widget.addWidget(self.page_2)
        self.gridLayout_2.addWidget(self.Header_Widget, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.Main_menu, 0, 2, 1, 1)
        self.icon_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_widget.setStyleSheet("\n"
"\n"
"QWidget{\n"
"background: rgb(55, 113, 233);\n"
"}\n"
"\n"
"QPushButton{\n"
"color:black;\n"
"text-align: center;\n"
"height : 30 px;\n"
"border :None;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"\n"
"QPushButton:checked{\n"
"background-color: #F5FAFE;\n"
"color: #1F95EF;\n"
"font-weight: bold;\n"
"\n"
"}\n"
"")
        self.icon_widget.setObjectName("icon_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.icon_widget)
        self.verticalLayout.setContentsMargins(-1, 50, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.icon_widget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setHandleWidth(15)
        self.splitter.setObjectName("splitter")
        self.HomeButton = QtWidgets.QPushButton(self.splitter)
        self.HomeButton.setMaximumSize(QtCore.QSize(24, 30))
        self.HomeButton.setText("")
        self.HomeButton.setIcon(icon)
        self.HomeButton.setIconSize(QtCore.QSize(20, 20))
        self.HomeButton.setCheckable(True)
        self.HomeButton.setAutoExclusive(True)
        self.HomeButton.setObjectName("HomeButton")
        self.LoadDataButton = QtWidgets.QPushButton(self.splitter)
        self.LoadDataButton.setMaximumSize(QtCore.QSize(24, 30))
        self.LoadDataButton.setText("")
        self.LoadDataButton.setIcon(icon1)
        self.LoadDataButton.setIconSize(QtCore.QSize(20, 20))
        self.LoadDataButton.setCheckable(True)
        self.LoadDataButton.setAutoExclusive(True)
        self.LoadDataButton.setObjectName("LoadDataButton")
        self.SearchButton = QtWidgets.QPushButton(self.splitter)
        self.SearchButton.setMaximumSize(QtCore.QSize(24, 30))
        self.SearchButton.setText("")
        self.SearchButton.setIcon(icon2)
        self.SearchButton.setIconSize(QtCore.QSize(20, 20))
        self.SearchButton.setCheckable(True)
        self.SearchButton.setAutoExclusive(True)
        self.SearchButton.setObjectName("SearchButton")
        self.verticalLayout.addWidget(self.splitter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 249, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.MoreInfoButton = QtWidgets.QPushButton(self.icon_widget)
        self.MoreInfoButton.setText("")
        self.MoreInfoButton.setIcon(icon3)
        self.MoreInfoButton.setIconSize(QtCore.QSize(20, 20))
        self.MoreInfoButton.setCheckable(True)
        self.MoreInfoButton.setAutoExclusive(True)
        self.MoreInfoButton.setObjectName("MoreInfoButton")
        self.verticalLayout.addWidget(self.MoreInfoButton)
        self.gridLayout.addWidget(self.icon_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Header_Widget.setCurrentIndex(3)
        self.MenuButton.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.SearchButton.toggled['bool'].connect(self.SearchButton_2.setChecked) # type: ignore
        self.LoadDataButton.toggled['bool'].connect(self.LoadDataButton_2.setChecked) # type: ignore
        self.HomeButton.toggled['bool'].connect(self.HomeButton_2.setChecked) # type: ignore
        self.HomeButton_2.toggled['bool'].connect(self.HomeButton.setChecked) # type: ignore
        self.LoadDataButton_2.toggled['bool'].connect(self.LoadDataButton.setChecked) # type: ignore
        self.SearchButton_2.toggled['bool'].connect(self.SearchButton.setChecked) # type: ignore
        self.MoreInfoButton.toggled['bool'].connect(self.MoreInfoButton_2.setChecked) # type: ignore
        self.MoreInfoButton_2.toggled['bool'].connect(self.MoreInfoButton.setChecked) # type: ignore
        self.MenuButton.toggled['bool'].connect(self.icon_widget.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HomeButton_2.setText(_translate("MainWindow", "Home"))
        self.LoadDataButton_2.setText(_translate("MainWindow", "Load Data  "))
        self.SearchButton_2.setText(_translate("MainWindow", "Search"))
        self.MoreInfoButton_2.setText(_translate("MainWindow", "More Info"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">GEOHAZARDS PROJECT</span></p></body></html>"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt; color:#000000;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; color:#000000;\">HOME PAGE</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt; color:#000000;\"><br /></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt; color:#000000;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; color:#000000;\">SEARCH</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt; color:#000000;\"><br /></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt; color:#000000;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; color:#000000;\">More INFO</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:36pt; color:#000000;\"><br /></p></body></html>"))
        self.pushButton_LoadData.setText(_translate("MainWindow", "Load Data"))
