# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singleplot.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ViewWaveForm import Ui_MainWindow_ViewWaveForm

class Ui_MainWindow_SingleChannel(object):

    def openWaveForm(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_ViewWaveForm()
        self.ui.setupUi(self.window)
        self.window.show()
        
    
    def setupUi(self, MainWindow_SingleChannel):
        MainWindow_SingleChannel.setObjectName("MainWindow_SingleChannel")
        MainWindow_SingleChannel.resize(800, 600)
        self.centralwidget_SingleChannel = QtWidgets.QWidget(MainWindow_SingleChannel)
        self.centralwidget_SingleChannel.setObjectName("centralwidget_SingleChannel")
        self.frame_SingleChannel = QtWidgets.QFrame(self.centralwidget_SingleChannel)
        self.frame_SingleChannel.setGeometry(QtCore.QRect(70, 30, 671, 531))
        self.frame_SingleChannel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SingleChannel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SingleChannel.setObjectName("frame_SingleChannel")
        self.frame_2_SingleChannel = QtWidgets.QFrame(self.frame_SingleChannel)
        self.frame_2_SingleChannel.setGeometry(QtCore.QRect(230, 20, 341, 41))
        self.frame_2_SingleChannel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_SingleChannel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_SingleChannel.setObjectName("frame_2_SingleChannel")
        self.textBrowser_SingleChannel = QtWidgets.QTextBrowser(self.frame_2_SingleChannel)
        self.textBrowser_SingleChannel.setGeometry(QtCore.QRect(0, 0, 351, 41))
        self.textBrowser_SingleChannel.setObjectName("textBrowser_SingleChannel")
        self.frame_3_SingleChannel = QtWidgets.QFrame(self.frame_SingleChannel)
        self.frame_3_SingleChannel.setGeometry(QtCore.QRect(150, 80, 501, 331))
        self.frame_3_SingleChannel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_SingleChannel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_SingleChannel.setObjectName("frame_3_SingleChannel")
        self.MplWidget_SinglePlot = MplWidget(self.frame_3_SingleChannel)
        self.MplWidget_SinglePlot.setGeometry(QtCore.QRect(10, 10, 480, 321))
        self.MplWidget_SinglePlot.setMinimumSize(QtCore.QSize(480, 320))
        self.MplWidget_SinglePlot.setObjectName("MplWidget_SinglePlot")
        self.pushButton_back_SingleChannel = QtWidgets.QPushButton(self.frame_SingleChannel)
        self.pushButton_back_SingleChannel.setGeometry(QtCore.QRect(150, 420, 141, 31))
        self.pushButton_back_SingleChannel.setObjectName("pushButton_back_SingleChannel")
        self.pushButton_next_SingleChannel = QtWidgets.QPushButton(self.frame_SingleChannel)
        self.pushButton_next_SingleChannel.setGeometry(QtCore.QRect(510, 420, 141, 31))
        self.pushButton_next_SingleChannel.setObjectName("pushButton_next_SingleChannel")
        self.label_2_SingleChannel = QtWidgets.QLabel(self.frame_SingleChannel)
        self.label_2_SingleChannel.setGeometry(QtCore.QRect(10, 120, 51, 20))
        self.label_2_SingleChannel.setObjectName("label_2_SingleChannel")
        self.lineEdit_ch_SingleChannel = QtWidgets.QLineEdit(self.frame_SingleChannel)
        self.lineEdit_ch_SingleChannel.setGeometry(QtCore.QRect(10, 140, 111, 21))
        self.lineEdit_ch_SingleChannel.setText("")
        self.lineEdit_ch_SingleChannel.setObjectName("lineEdit_ch_SingleChannel")
        self.label_3_SingleChannel = QtWidgets.QLabel(self.frame_SingleChannel)
        self.label_3_SingleChannel.setGeometry(QtCore.QRect(10, 190, 111, 20))
        self.label_3_SingleChannel.setText("")
        self.label_3_SingleChannel.setObjectName("label_3_SingleChannel")
        self.pushButton_next_2 = QtWidgets.QPushButton(self.frame_SingleChannel, clicked = lambda : self.openWaveForm())
        self.pushButton_next_2.setGeometry(QtCore.QRect(510, 470, 141, 31))
        self.pushButton_next_2.setObjectName("pushButton_next_2")
        MainWindow_SingleChannel.setCentralWidget(self.centralwidget_SingleChannel)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_SingleChannel)
        self.statusbar.setObjectName("statusbar")
        MainWindow_SingleChannel.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_SingleChannel)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_SingleChannel)

    def retranslateUi(self, MainWindow_SingleChannel):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_SingleChannel.setWindowTitle(_translate("MainWindow_SingleChannel", "MainWindow"))
        self.textBrowser_SingleChannel.setHtml(_translate("MainWindow_SingleChannel", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Testing Single Channel</span></p></body></html>"))
        self.pushButton_back_SingleChannel.setText(_translate("MainWindow_SingleChannel", "Back"))
        self.pushButton_next_SingleChannel.setText(_translate("MainWindow_SingleChannel", "Next"))
        self.label_2_SingleChannel.setText(_translate("MainWindow_SingleChannel", "Channel"))
        self.pushButton_next_2.setText(_translate("MainWindow_SingleChannel", "View Waveform"))
from mplwidget import MplWidget



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_MainWindow_SingleChannel = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_SingleChannel
    ui.setupUi(Ui_MainWindow_SingleChannel)
    Ui_MainWindow_SingleChannel.show()
    sys.exit(app.exec_())
