# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startup.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import (NavigationToolbar2QT as NavigationToolbar)
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backend_bases import NavigationToolbar2
from BandPass import Ui_MainWindow_BandPass
from BandStop import Ui_MainWindow_BandStop
from Lowpass import Ui_MainWindow_Lowpass
from lowpass_cheby_ import Ui_MainWindow_LowpassCheby
from HighpassFilter import Ui_MainWindow_HighPass
from envelope import Ui_MainWindow_envelope
from plotWindow import Ui_plotWindow
from plot_window import Ui_MainWindow
from frequency_analysis import Ui_MainWindow_FreqAnalysis

class Ui_MainWindow2(object):
    def __init__(self, data):
        self.data = data
    # def openwindow_Bandpass(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_MainWindow_BandPass()
    #     self.ui.setupUi(self.window)
    #     self.window.show()
    def openwindow_BandStop(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_BandStop()
        self.ui.setupUi(self.window)
        self.window.show()
        
    def openwindow_Lowpass(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_Lowpass()
        self.ui.setupUi(self.window)
        self.window.show()
    def openwindow_Lowpass_cheby_2(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_LowpassCheby()
        self.ui.setupUi(self.window)
        self.window.show()
    def openwindow_Frequency_Analysis(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_FreqAnalysis(self.data)
        self.ui.setupUi(self.window)
        self.window.show()
    def openwindow_Envelope(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow_envelope()
        self.ui.setupUi(self.window)
        self.window.addToolBar(NavigationToolbar(self.ui2.MplWidget.canvas, self.window))

    #this one works so far 
    def openwindow_plotWindow(self):
        self.window = QtWidgets.QMainWindow()  # Create a new QMainWindow
        self.ui2 = Ui_MainWindow(self.data)  # Initialize Ui_plotWindow with data
        self.ui2.setupUi(self.window)  # Set up the UI
        self.window.addToolBar(NavigationToolbar(self.ui2.MplWidget.canvas, self.window))   # Add a toolbar for navigation
        self.window.show()  # Show the second window

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background: rgb(253, 253, 249)\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setStyleSheet("QWidget{\n"
"background: #0276FF;\n"
"border-radius: 20px;\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setMinimumSize(QtCore.QSize(281, 123))
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_2,clicked = lambda : self.openwindow_plotWindow())
        self.pushButton_8.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout.addWidget(self.pushButton_8)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2, clicked = lambda: self.openwindow_Frequency_Analysis())
        self.pushButton_5.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2,clicked = lambda : self.openwindow_plotWindow())
        self.pushButton_2.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2,clicked = lambda : self.openwindow_plotWindow())
        self.pushButton_3.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2,clicked = lambda : self.openwindow_plotWindow())
        self.pushButton_6.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2,clicked = lambda : self.openwindow_plotWindow())
        self.pushButton_4.setStyleSheet("\n"
"QPushButton {\n"
"  background:  #000000;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #FFFFFF;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}\n"
"\n"
"\n"
"QPushButton:hover {\n"
"  background: #FFFFFF;\n"
"  border-radius: 10px;\n"
"  box-shadow: #5E5DF0 0 10px 20px -10px;\n"
"  box-sizing: border-box;\n"
"  color: #000000;\n"
"  cursor: pointer;\n"
"  font-size: 16px;\n"
"  font-weight: 700;\n"
"  line-height: 24px;\n"
"  opacity: 1;\n"
"  outline: 0 solid transparent;\n"
"  padding: 8px 18px;\n"
"  user-select: none;\n"
"  -webkit-user-select: none;\n"
"  touch-action: manipulation;\n"
"  width: fit-content;\n"
"  word-break: break-word;\n"
"  border: 0;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.gridLayout_3.addWidget(self.frame_2, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_8.setText(_translate("MainWindow", "BandPass"))
        self.pushButton_5.setText(_translate("MainWindow", "Frequency Analysis"))
        self.pushButton_2.setText(_translate("MainWindow", "Band Stop"))
        self.pushButton_3.setText(_translate("MainWindow", "Lowpass"))
        self.pushButton_6.setText(_translate("MainWindow", "Envelope"))
        self.pushButton_4.setText(_translate("MainWindow", "Lowpass cheby 2"))

    
