# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ViewWaveForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow_ViewWaveForm(object):
    def setupUi(self, MainWindow_ViewWaveForm):
        MainWindow_ViewWaveForm.setObjectName("MainWindow_ViewWaveForm")
        MainWindow_ViewWaveForm.resize(800, 600)
        self.centralwidget_ViewWaveForm = QtWidgets.QWidget(MainWindow_ViewWaveForm)
        self.centralwidget_ViewWaveForm.setObjectName("centralwidget_ViewWaveForm")
        self.frame_SingleChannel_ViewWaveForm = QtWidgets.QFrame(self.centralwidget_ViewWaveForm)
        self.frame_SingleChannel_ViewWaveForm.setGeometry(QtCore.QRect(20, 0, 641, 511))
        self.frame_SingleChannel_ViewWaveForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_SingleChannel_ViewWaveForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SingleChannel_ViewWaveForm.setObjectName("frame_SingleChannel_ViewWaveForm")
        self.frame_2_SingleChannel_ViewWaveForm = QtWidgets.QFrame(self.frame_SingleChannel_ViewWaveForm)
        self.frame_2_SingleChannel_ViewWaveForm.setGeometry(QtCore.QRect(140, 20, 341, 41))
        self.frame_2_SingleChannel_ViewWaveForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2_SingleChannel_ViewWaveForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2_SingleChannel_ViewWaveForm.setObjectName("frame_2_SingleChannel_ViewWaveForm")
        self.textBrowser_SingleChannel_ViewWaveForm = QtWidgets.QTextBrowser(self.frame_2_SingleChannel_ViewWaveForm)
        self.textBrowser_SingleChannel_ViewWaveForm.setGeometry(QtCore.QRect(0, 0, 351, 41))
        self.textBrowser_SingleChannel_ViewWaveForm.setObjectName("textBrowser_SingleChannel_ViewWaveForm")
        self.frame_3_SingleChannel_ViewWaveForm = QtWidgets.QFrame(self.frame_SingleChannel_ViewWaveForm)
        self.frame_3_SingleChannel_ViewWaveForm.setGeometry(QtCore.QRect(70, 80, 501, 331))
        self.frame_3_SingleChannel_ViewWaveForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3_SingleChannel_ViewWaveForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3_SingleChannel_ViewWaveForm.setObjectName("frame_3_SingleChannel_ViewWaveForm")
        self.MplWidget_SinglePlot_ViewWaveForm = MplWidget(self.frame_3_SingleChannel_ViewWaveForm)
        self.MplWidget_SinglePlot_ViewWaveForm.setGeometry(QtCore.QRect(10, 10, 480, 321))
        self.MplWidget_SinglePlot_ViewWaveForm.setMinimumSize(QtCore.QSize(480, 320))
        self.MplWidget_SinglePlot_ViewWaveForm.setObjectName("MplWidget_SinglePlot_ViewWaveForm")
        self.pushButton_back_SingleChannel_ViewWaveForm = QtWidgets.QPushButton(self.frame_SingleChannel_ViewWaveForm)
        self.pushButton_back_SingleChannel_ViewWaveForm.setGeometry(QtCore.QRect(70, 420, 141, 31))
        self.pushButton_back_SingleChannel_ViewWaveForm.setObjectName("pushButton_back_SingleChannel_ViewWaveForm")
        self.pushButton_next_SingleChannel_ViewWaveForm = QtWidgets.QPushButton(self.frame_SingleChannel_ViewWaveForm)
        self.pushButton_next_SingleChannel_ViewWaveForm.setGeometry(QtCore.QRect(430, 420, 141, 31))
        self.pushButton_next_SingleChannel_ViewWaveForm.setObjectName("pushButton_next_SingleChannel_ViewWaveForm")
        self.label_3_SingleChannel_ViewWaveForm = QtWidgets.QLabel(self.frame_SingleChannel_ViewWaveForm)
        self.label_3_SingleChannel_ViewWaveForm.setGeometry(QtCore.QRect(10, 190, 111, 20))
        self.label_3_SingleChannel_ViewWaveForm.setText("")
        self.label_3_SingleChannel_ViewWaveForm.setObjectName("label_3_SingleChannel_ViewWaveForm")
        MainWindow_ViewWaveForm.setCentralWidget(self.centralwidget_ViewWaveForm)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_ViewWaveForm)
        self.statusbar.setObjectName("statusbar")
        MainWindow_ViewWaveForm.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_ViewWaveForm)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_ViewWaveForm)

    def retranslateUi(self, MainWindow_ViewWaveForm):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_ViewWaveForm.setWindowTitle(_translate("MainWindow_ViewWaveForm", "MainWindow"))
        self.textBrowser_SingleChannel_ViewWaveForm.setHtml(_translate("MainWindow_ViewWaveForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">WaveForm</span></p></body></html>"))
        self.pushButton_back_SingleChannel_ViewWaveForm.setText(_translate("MainWindow_ViewWaveForm", "Back"))
        self.pushButton_next_SingleChannel_ViewWaveForm.setText(_translate("MainWindow_ViewWaveForm", "Next"))
from mplwidget import MplWidget




if __name__ == "__main__":
    import sys
    app = QtWidgets.Ui_MainWindow_ViewWaveForm(sys.argv)
    Ui_MainWindow_SingleChannel = Ui_MainWindow_ViewWaveForm.QMainWindow()
    ui = Ui_MainWindow_SingleChannel
    ui.setupUi(Ui_MainWindow_ViewWaveForm)
    Ui_MainWindow_ViewWaveForm.show()
    sys.exit(app.exec_())
